# Generated by Django 6.0.4 on 2026-04-14 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('budgets', '0001_initial'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('budget_warning', 'Budget warning'), ('budget_exceeded', 'Budget exceeded'), ('debt_overdue', 'Debt overdue'), ('system_info', 'System info'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('related_debt_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_budget', models.ForeignKey(blank=True, db_column='related_budget_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='budgets.budget')),
                ('related_expense', models.ForeignKey(blank=True, db_column='related_expense_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='expenses.expense')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'alert',
                'verbose_name_plural': 'alerts',
                'db_table': 'alerts',
                'indexes': [models.Index(fields=['user'], name='idx_alerts_user_id'), models.Index(fields=['alert_type'], name='idx_alerts_alert_type'), models.Index(fields=['is_read'], name='idx_alerts_is_read'), models.Index(fields=['created_at'], name='idx_alerts_created_at'), models.Index(fields=['user', 'is_read', 'created_at'], name='idx_alerts_user_read_at')],
            },
        ),
    ]
