# Generated by Django 6.0.4 on 2026-04-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('budget_warning', 'Cảnh báo ngân sách'), ('budget_exceeded', 'Vượt ngân sách'), ('debt_overdue', 'Nợ quá hạn'), ('system_info', 'Thông tin hệ thống'), ('other', 'Khác')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('info', 'Thông tin'), ('warning', 'Cần chú ý'), ('critical', 'Nghiêm trọng')], max_length=10),
        ),
    ]
