# Generated by Django 6.0.4 on 2026-04-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=255, null=True)),
                ('default_currency', models.CharField(blank=True, default='VND', max_length=10, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'db_table': 'users',
                'indexes': [models.Index(fields=['role'], name='idx_users_role'), models.Index(fields=['is_active'], name='idx_users_is_active')],
            },
        ),
    ]
