{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.hostPath) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nufi.mediaPvcName" . }}
  labels:
    {{- include "nufi.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.media.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size | quote }}
  {{- if .Values.persistence.media.storageClassName }}
  storageClassName: {{ .Values.persistence.media.storageClassName | quote }}
  {{- end }}
---
{{- end }}
{{- if .Values.persistence.reports.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nufi.reportsPvcName" . }}
  labels:
    {{- include "nufi.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.reports.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.reports.size | quote }}
  {{- if .Values.persistence.reports.storageClassName }}
  storageClassName: {{ .Values.persistence.reports.storageClassName | quote }}
  {{- end }}
{{- end }}
