{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nufi.secretName" . }}
  labels:
    {{- include "nufi.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secret.secretKey | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.secret.djangoSuperuserPassword | quote }}
  GOOGLE_OAUTH_CLIENT_ID: {{ .Values.secret.googleOauthClientId | quote }}
  GOOGLE_OAUTH_CLIENT_SECRET: {{ .Values.secret.googleOauthClientSecret | quote }}
{{- end }}
