{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nufi.fullname" . }}
  labels:
    {{- include "nufi.labels" . | nindent 4 }}
    release: {{ .Values.monitoring.serviceMonitor.releaseLabel | quote }}
spec:
  selector:
    matchLabels:
      {{- include "nufi.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.serviceMonitor.path | quote }}
      interval: {{ .Values.monitoring.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout | quote }}
{{- end }}
