# Generated by Django 6.0.4 on 2026-04-14 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('both', 'Both')], default='expense', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('color_code', models.CharField(blank=True, max_length=20, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
                'indexes': [models.Index(fields=['user'], name='idx_categories_user_id'), models.Index(fields=['category_type'], name='idx_categories_category_type'), models.Index(fields=['is_default'], name='idx_categories_is_default'), models.Index(fields=['is_active'], name='idx_categories_is_active')],
                'constraints': [models.UniqueConstraint(fields=('user', 'category_name'), name='uq_categories_user_name')],
            },
        ),
    ]
