# Generated by Django 6.0.4 on 2026-04-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='category_type',
            field=models.CharField(choices=[('income', 'Thu nhập'), ('expense', 'Chi tiêu'), ('both', 'Cả thu và chi')], default='expense', max_length=10),
        ),
    ]
