# Generated by Django 6.0.4 on 2026-04-14 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('budget_name', models.CharField(max_length=120)),
                ('budget_scope', models.CharField(choices=[('overall', 'Overall'), ('category', 'Category')], max_length=20)),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveSmallIntegerField()),
                ('spending_limit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('warning_percent', models.DecimalField(decimal_places=2, default=80, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='categories.expensecategory')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'budget',
                'verbose_name_plural': 'budgets',
                'db_table': 'budgets',
                'indexes': [models.Index(fields=['user'], name='idx_budgets_user_id'), models.Index(fields=['category'], name='idx_budgets_category_id'), models.Index(fields=['period_year', 'period_month'], name='idx_budgets_period_year_month'), models.Index(fields=['user', 'period_year', 'period_month'], name='idx_budgets_user_year_month')],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_month__gte', 1), ('period_month__lte', 12)), name='chk_budgets_period_month'), models.CheckConstraint(condition=models.Q(('spending_limit__gt', 0)), name='chk_budgets_spending_limit'), models.CheckConstraint(condition=models.Q(('warning_percent__gt', 0), ('warning_percent__lte', 100)), name='chk_budgets_warning_percent')],
            },
        ),
    ]
