# Generated by Django 6.0.4 on 2026-04-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_scope',
            field=models.CharField(choices=[('overall', 'Ngân sách tổng'), ('category', 'Theo danh mục')], max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('active', 'Đang dùng'), ('inactive', 'Tạm tắt'), ('closed', 'Đã đóng')], default='active', max_length=10),
        ),
    ]
