# Generated by Django 6.0.4 on 2026-04-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('expenses', '0001_initial'),
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingGroup',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Đang dùng'), ('inactive', 'Tạm tắt'), ('archived', 'Đã lưu trữ')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(db_column='owner_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='SharedTransaction',
            fields=[
                ('shared_transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('visibility_status', models.CharField(choices=[('visible', 'Đang hiển thị'), ('hidden', 'Đã ẩn')], default='visible', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(blank=True, db_column='expense_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_records', to='expenses.expense')),
                ('income', models.ForeignKey(blank=True, db_column='income_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_records', to='income.income')),
                ('shared_by_user', models.ForeignKey(db_column='shared_by_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='shared_transactions', to='accounts.userprofile')),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='shared_transactions', to='sharing.sharinggroup')),
            ],
            options={
                'db_table': 'shared_transactions',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('group_member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_role', models.CharField(choices=[('owner', 'Chủ nhóm'), ('member', 'Thành viên')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Đang tham gia'), ('left', 'Đã rời'), ('removed', 'Đã xóa')], default='active', max_length=20)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='accounts.userprofile')),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='sharing.sharinggroup')),
            ],
            options={
                'db_table': 'group_members',
            },
        ),
        migrations.AddIndex(
            model_name='sharinggroup',
            index=models.Index(fields=['owner_user'], name='idx_groups_owner_user_id'),
        ),
        migrations.AddIndex(
            model_name='sharinggroup',
            index=models.Index(fields=['status'], name='idx_groups_status'),
        ),
        migrations.AddIndex(
            model_name='sharedtransaction',
            index=models.Index(fields=['group'], name='idx_shared_tx_group'),
        ),
        migrations.AddIndex(
            model_name='sharedtransaction',
            index=models.Index(fields=['shared_by_user'], name='idx_shared_tx_user'),
        ),
        migrations.AddIndex(
            model_name='sharedtransaction',
            index=models.Index(fields=['expense'], name='idx_shared_tx_expense'),
        ),
        migrations.AddIndex(
            model_name='sharedtransaction',
            index=models.Index(fields=['income'], name='idx_shared_tx_income'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group'], name='idx_group_members_group_id'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['user'], name='idx_group_members_user_id'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['status'], name='idx_group_members_status'),
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='uq_group_members_group_user'),
        ),
    ]
