# Generated by Codex on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Chờ xác nhận'),
                    ('active', 'Đang tham gia'),
                    ('left', 'Đã rời'),
                    ('removed', 'Đã xóa'),
                ],
                default='active',
                max_length=20,
            ),
        ),
    ]
