# Generated by Codex on 2026-04-18

from django.db import migrations


def add_pending_status_to_mysql_enum(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SHOW COLUMNS FROM `group_members` LIKE 'status'")
        row = cursor.fetchone()
        column_type = row[1] if row else ''
        if 'pending' in column_type:
            return

        cursor.execute(
            """
            ALTER TABLE `group_members`
            MODIFY `status`
            ENUM('pending', 'active', 'left', 'removed')
            NOT NULL DEFAULT 'active'
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_groupmember_pending_status'),
    ]

    operations = [
        migrations.RunPython(add_pending_status_to_mysql_enum, migrations.RunPython.noop),
    ]
