# Generated by Django 6.0.4 on 2026-04-14 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank_account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('e_wallet', 'E-wallet'), ('other', 'Other')], max_length=20)),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number_masked', models.CharField(blank=True, max_length=30, null=True)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'bank account',
                'verbose_name_plural': 'bank accounts',
                'db_table': 'bank_accounts',
                'indexes': [models.Index(fields=['user'], name='idx_bank_accounts_user_id'), models.Index(fields=['account_type'], name='idx_bank_accounts_account_type'), models.Index(fields=['is_active'], name='idx_bank_accounts_is_active')],
            },
        ),
    ]
