# Generated by Django 6.0.4 on 2026-04-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('bank', 'Tài khoản ngân hàng'), ('cash', 'Tiền mặt'), ('e_wallet', 'Ví điện tử'), ('other', 'Khác')], max_length=20),
        ),
    ]
