# Generated by Django 6.0.4 on 2026-04-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bank_accounts', '0002_alter_bankaccount_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('debt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('debt_type', models.CharField(choices=[('i_owe', 'Mình nợ'), ('owed_to_me', 'Người khác nợ mình')], max_length=20)),
                ('counterparty_name', models.CharField(max_length=150)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Đang theo dõi'), ('partially_paid', 'Đã trả một phần'), ('paid', 'Đã trả xong'), ('overdue', 'Quá hạn')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'debts',
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('debt_payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, db_column='bank_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_payments', to='bank_accounts.bankaccount')),
                ('debt', models.ForeignKey(db_column='debt_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debts.debt')),
            ],
            options={
                'db_table': 'debt_payments',
            },
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['user'], name='idx_debts_user_id'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['status'], name='idx_debts_status'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['due_date'], name='idx_debts_due_date'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['user', 'status', 'due_date'], name='idx_debts_user_status_due'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', 0)), name='chk_debts_original_amount'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_amount__gte', 0)), name='chk_debts_remaining_amount'),
        ),
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['debt'], name='idx_debt_payments_debt_id'),
        ),
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['payment_date'], name='idx_debt_payments_date'),
        ),
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['bank_account'], name='idx_debt_payments_account'),
        ),
        migrations.AddConstraint(
            model_name='debtpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_debt_payments_amount'),
        ),
    ]
