# Generated by Django 6.0.4 on 2026-04-14 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bank_accounts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expense_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank'), ('e_wallet', 'E-wallet'), ('credit_card', 'Credit card'), ('other', 'Other')], max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, db_column='bank_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='bank_accounts.bankaccount')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='categories.expensecategory')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'db_table': 'expenses',
                'indexes': [models.Index(fields=['user'], name='idx_expenses_user_id'), models.Index(fields=['category'], name='idx_expenses_category_id'), models.Index(fields=['bank_account'], name='idx_expenses_bank_account_id'), models.Index(fields=['expense_date'], name='idx_expenses_expense_date'), models.Index(fields=['user', 'expense_date'], name='idx_expenses_user_expense_date'), models.Index(fields=['user', 'category', 'expense_date'], name='idx_exp_user_cat_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_expenses_amount')],
            },
        ),
    ]
